<?php get_header(); ?>
	<?php get_template_part('templates/header') ?>
	<?php get_template_part('templates/banner') ?>
	<?php get_template_part('templates/cursos-icms') ?>
	<?php get_template_part('templates/instagram') ?>
	<?php get_template_part('templates/noticias') ?>
	<?php get_template_part('templates/legislacoes') ?>
	<?php get_template_part('templates/depoimentos') ?>
	<?php get_template_part('templates/parceiros') ?>
<?php get_footer(); ?>