<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_detalhes-curso',
		'title' => 'Detalhes - CURSO',
		'fields' => array (
			array (
				'key' => 'field_5790c2471a858',
				'label' => 'Primeiro Lote - Data',
				'name' => 'primeiro_lote_data',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5790c30f68e82',
				'label' => 'Primeiro Lote - Valor',
				'name' => 'primeiro_lote_valor',
				'type' => 'number',
				'instructions' => 'Insira o valor do PRIMEIRO LOTE a ser disponibilizado',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5790c2ca68e80',
				'label' => 'Segundo Lote - Data',
				'name' => 'segundo_lote_data',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5790c2bb68e7f',
				'label' => 'Segundo Lote - Valor',
				'name' => 'segundo_lote_valor',
				'type' => 'number',
				'instructions' => 'Insira o valor do SEGUNDO LOTE a ser disponibilizado',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5790c2dd68e81',
				'label' => 'Terceiro Lote - Data',
				'name' => 'terceiro_lote_data',
				'type' => 'date_picker',
				'date_format' => 'yy-mm-dd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			
			array (
				'key' => 'field_578e30c1dab8e',
				'label' => 'Professores',
				'name' => 'professores',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'professor',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_578e318ded04d',
				'label' => 'Horários',
				'name' => 'horarios',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_578e319ded04e',
				'label' => 'Objetivos',
				'name' => 'objetivos',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_578e31aaed04f',
				'label' => 'Público Alvo',
				'name' => 'publico_alvo',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_578e31c3ed050',
				'label' => 'Conteúdo Programático',
				'name' => 'conteudo_programatico',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_578e321aed053',
				'label' => 'Carga Horária',
				'name' => 'carga_horaria',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578e896fee5cf',
				'label' => 'Período',
				'name' => 'periodo',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578e89bdee5d0',
				'label' => 'Local',
				'name' => 'local',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578e8a04ee5d1',
				'label' => 'Coordenação',
				'name' => 'coordenacao',
				'type' => 'text',
				'default_value' => 'Paulo Almada',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578e8a24c2677',
				'label' => 'Contatos',
				'name' => 'contatos',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578e8a2ec2678',
				'label' => 'E-mail',
				'name' => 'email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'curso',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
			'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
